export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const RANK_DATA = 'RANK_DATA';
export const RANK_DATA_SUCCESS = 'RANK_DATA_SUCCESS';
export const RANK_DATA_FAILURE = 'RANK_DATA_FAILURE';

export const QUEST_DATA = 'QUEST_DATA';
export const QUEST_DATA_SUCCESS = 'QUEST_DATA_SUCCESS';
export const QUEST_DATA_FAILURE = 'QUEST_DATA_FAILURE';

export const HISTORY_DATA = 'HISTORY_DATA';
export const HISTORY_DATA_SUCCESS = 'HISTORY_DATA_SUCCESS';
export const HISTORY_DATA_FAILURE = 'HISTORY_DATA_FAILURE';