export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const RANK_DATA = 'RANK_DATA';
export const RANK_DATA_SUCCESS = 'RANK_DATA_SUCCESS';
export const RANK_DATA_FAILURE = 'RANK_DATA_FAILURE';